spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ciphermesh_identity}
    username: ${DB_USER:ciphermesh}
    password: ${DB_PASSWORD:ciphermesh}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

ciphermesh:
  identity:
    prekeys:
      low-watermark: 10

server:
  port: 8081
