spring:
  application:
    name: delivery-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: delivery
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.ciphermesh.events
        spring.json.value.default.type: com.ciphermesh.events.MessageEnvelopeEvent

ciphermesh:
  jwt:
    secret: ${CIPHERMESH_JWT_SECRET:dev-secret-change-me-please-use-a-long-random-value-0123456789}

server:
  port: 8082
